TARGET_OPTIONS = --cpu-type picorv32 --rom-init ../ice40-playground/projects/riscv_usb/fw/fw_app.bin
VERILOG_SOURCES += $(WPWD)/../ice40-playground/cores/usb/rtl/*.v \
				   $(WPWD)/../yosys/techlibs/ice40/cells_sim.v \
				   $(WPWD)/../ice40-playground/cores/misc/rtl/*.v \
				   $(WPWD)/../ice40-playground/projects/riscv_usb/rtl/*.v \
				   $(WPWD)/../ice40-playground/projects/riscv_usb/sim/*.v
COMPILE_ARGS += -I $(WPWD)/../ice40-playground/cores/usb/rtl

sim: $(PWD)/dut.v
	rm -f results.xml
	make -C ../ice40-playground/projects/riscv_usb CROSS=riscv64-unknown-elf fw/boot_app.hex
	cp ../ice40-playground/projects/riscv_usb/fw/boot_app.hex boot.hex
	cd ../ice40-playground/projects/riscv_usb/fw \
		python3 /bin2hex.py fw/fw_app.bin fw/fw_app.hex
	cp ../ice40-playground/projects/riscv_usb/fw/fw_app.hex firmware.hex
	../ice40-playground/cores/usb/utils/microcode.py > usb_trans_mc.hex
	cp -r build/gateware/mem.init .
	make results.xml

clean::
	rm usb_trans_mc.hex boot.hex
