TARGET_OPTIONS = --cpu-type vexriscv --variant eptri --ram-init zephyr.bin
VERILOG_SOURCES += $(WPWD)/../litex/litex/soc/cores/cpu/vexriscv/verilog/VexRiscv_Lite.v
COMPILE_ARGS += -I $(WPWD)/../litex/litex/soc/cores/cpu/vexriscv/verilog/VexRiscv_Lite.v
export DUT_CSRS = csr.csv
export PATH := ../../../litex-vexriscv-build/toolchain/riscv64-unknown-elf-gcc-8.2.0-2019.05.3-x86_64-linux-ubuntu14/bin:../../../zvb/zvb-ci/litex-fpga/riscv-gcc/bin:$(PATH)

export PYTHONPATH +=../litex/litex:../migen:../litedram:../valentyusb:$(PYTHONPATH)
test:
	echo $(PYTHONPATH)
	ptpython
